name: Monitoring Pipeline

# =========================
# EVENTOS QUE DISPARAM O PIPELINE
# =========================
on:

  workflow_dispatch:

  push:
    branches:
      - main

# =========================
# PERMISSÕES NECESSÁRIAS
# =========================
permissions:
  id-token: write
  contents: read

# =========================
# JOB PRINCIPAL
# =========================
jobs:

  monitoring:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # ETAPA 1 — CHECKOUT
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      # =========================
      # ETAPA 2 — AUTENTICAÇÃO AWS
      # =========================
      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: arn:aws:iam::597819997995:role/GitHubActionsRole
          aws-region: us-east-1

      # =========================
      # ETAPA 3 — VALIDAÇÃO DA SESSÃO AWS
      # =========================
      - name: Validate AWS Session

        run: |

          echo "========================================="
          echo "VALIDANDO SESSÃO AWS"
          echo "========================================="

          echo ""
          echo "Região AWS configurada:"
          aws configure get region

          echo ""
          echo "Validando identidade IAM autenticada..."
          aws sts get-caller-identity

          echo ""
          echo "Status:"
          echo "Autenticação AWS validada com sucesso."

          echo "========================================="

      # =========================
      # ETAPA 4 — VALIDAR REGIÃO AWS
      # =========================
      - name: Validate Current AWS Region

        run: |

          echo "========================================="
          echo "VALIDANDO REGIÃO AWS CONFIGURADA"
          echo "========================================="

          echo ""
          echo "Região atualmente configurada no runner:"
          aws configure get region

          echo ""
          echo "Status:"
          echo "Região AWS validada com sucesso."

          echo "========================================="

      # =========================
      # ETAPA 5 — LISTAR BUCKETS S3
      # =========================
      - name: List S3 Buckets

        run: |

          echo "========================================="
          echo "VALIDANDO ACESSO AO AMAZON S3"
          echo "========================================="

          echo ""
          echo "Listando buckets S3 disponíveis na conta AWS..."

          aws s3 ls

          echo ""
          echo "Status:"
          echo "Conectividade com Amazon S3 validada com sucesso."

          echo "========================================="
