name: Monitoring Pipeline

# =========================
# EVENTOS QUE DISPARAM O PIPELINE
# =========================
on:

  # Execução manual
  workflow_dispatch:

  # Execução automática via push
  push:
    branches:
      - main

# =========================
# PERMISSÕES NECESSÁRIAS
# =========================
permissions:
  id-token: write
  contents: read

# =========================
# JOB PRINCIPAL
# =========================
jobs:

  monitoring:

    # Runner oficial GitHub Linux
    runs-on: ubuntu-latest

    steps:

      # =========================
      # ETAPA 1 — CHECKOUT
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      # =========================
      # ETAPA 2 — AUTENTICAÇÃO AWS
      # =========================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # =========================
      # ETAPA 3 — VALIDAR SESSÃO AWS
      # =========================
      - name: Validate AWS Session
        run: |

          echo "Região AWS:"
          echo "$AWS_REGION"

          echo "Caller Identity:"
          aws sts get-caller-identity

      # =========================
      # ETAPA 4 — VALIDAR REGIÃO AWS
      # =========================
      - name: Validate Current AWS Region
        run: |

          echo "Região AWS configurada:"
          aws configure get region

      # =========================
      # ETAPA 5 — LISTAR BUCKETS S3
      # =========================
      - name: List S3 Buckets
        run: |

          echo "Listando buckets S3 disponíveis..."
          aws s3 ls
```