name: CI - SQL Server Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrongPassw0rd
        ports:
          - 1433:1433

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list

          sudo apt-get update

          sudo ACCEPT_EULA=Y apt-get install -y \
            mssql-tools18 \
            unixodbc-dev

      - name: Wait SQL Server start
        run: sleep 25

      - name: Test SQL Server connection
        run: |
          /opt/mssql-tools18/bin/sqlcmd \
          -S localhost \
          -U sa \
          -P 'YourStrongPassw0rd' \
          -Q "SELECT @@VERSION" \
          -C

      - name: Run validation script
        run: |
          chmod +x tests/test_db_objects.sh
          ./tests/test_db_objects.sh
